version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          major-minor-patch:
              applies-to: version-updates
              update-types:
                  - 'major'
                  - 'minor'
                  - 'patch'
