version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      groups:
          major-minor-patch:
              applies-to: version-updates
              exclude-patterns:
                  - zigbee-herdsman-converters
                  # Don't upgrade zhc and sass (because of nasty deprecation warnings which can't be fixed due to Quasar)
                  - sass
              update-types:
                  - major
                  - minor
                  - patch
