version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      groups:
          major-minor-patch:
              applies-to: version-updates
              exclude-patterns:
                  - zigbee-herdsman-converters
              update-types:
                  - major
                  - minor
                  - patch
